name       : haskell-data-default
version    : 0.7.1.1
release    : 2
source     :
    - https://hackage.haskell.org/package/data-default-0.7.1.1/data-default-0.7.1.1.tar.gz : b0f95d279cd75cacaa8152a01590dc3460f7134f6840b37052abb3ba3cb2a511
license    : BSD-3-Clause
component  : programming.haskell
summary    : A class for types with a default value
description: "A class for types with a default value \n"
builddeps  :
    - data-default-instances-containers
    - data-default-instances-dlist
    - data-default-instances-old-locale
    - haskell-cabal-install
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
